# Generated by Django 5.0.6 on 2024-05-30 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=1)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_disponibles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesClub',
            fields=[
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalles', serialize=False, to='app_padel.club')),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion_larga', models.TextField()),
                ('numero_pistas', models.IntegerField()),
                ('imagen_principal', models.TextField()),
                ('imagen_secundaria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(default='', max_length=100)),
                ('activo', models.BooleanField(default=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='app_padel.club')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField()),
                ('activo', models.BooleanField(default=1)),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_padel.pista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
