# Generated by Django 4.2.5 on 2024-06-05 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_padel', '0002_remove_club_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='admin_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
